### PR TITLE
Massive dejankification

### PR DESCRIPTION
**Pull request by quantum9Innovation**
Ironically powered by [GitButler](https://gitbutler.com), which is supposed to prevent jank mega PRs like this one

### CODE REVIEW

**Comment by quantum9Innovation** [comment]
@couscousdude this also fixes failing Vercel deployment, which has to do with a prehistoric Node version configuration on Vercel and a libertarian `package.json` that refuses to combat prehistoric anarchism.

**Comment by couscousdude** [comment]
bro no way you're using the nextjs image tag everyone on stackoverflow just said disable that eslint rule because the nextjs image is trash

**Comment by quantum9Innovation** [comment]
wdym NextJS image is literally designed for performance so it can pre load images

It's just annoying to implement because NextJS devs are idiots but this is literally one of the few advantages of NextJS over react other than this rust build pipeline

LGTM and merge so I can continue innovation :shipit:

**Comment by couscousdude** [comment]
LGTM 🚢

**Review by couscousdude — COMMENTED** [review]
LGTM 🚢 ⚓

**Review by couscousdude — COMMENTED** [review]
SHIP IT!

**Review by couscousdude — COMMENTED** [review]
oops

**Review by couscousdude — APPROVED** [review]
OK SHIP IT NOW

**Comment by quantum9Innovation** [comment]
SHIPPED

**Pull request merged**
